// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type AccountType int16

const (
	AccountTypeEquity     AccountType = 0
	AccountTypeMargin     AccountType = 1
	AccountTypeDerivative AccountType = 2
)

var EnumNamesAccountType = map[AccountType]string{
	AccountTypeEquity:     "Equity",
	AccountTypeMargin:     "Margin",
	AccountTypeDerivative: "Derivative",
}

var EnumValuesAccountType = map[string]AccountType{
	"Equity":     AccountTypeEquity,
	"Margin":     AccountTypeMargin,
	"Derivative": AccountTypeDerivative,
}

func (v AccountType) String() string {
	if s, ok := EnumNamesAccountType[v]; ok {
		return s
	}
	return "AccountType(" + strconv.FormatInt(int64(v), 10) + ")"
}
