// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type BarType uint32

const (
	BarTypeDefault BarType = 0
	/// 1分钟线
	BarTypeMin1    BarType = 60
	/// 5分钟线
	BarTypeMin5    BarType = 300
	/// 15分钟线
	BarTypeMin15   BarType = 900
	/// 30分钟线
	BarTypeMin30   BarType = 1800
	/// 60分钟线
	BarTypeMin60   BarType = 3600
	/// 日线
	BarTypeDay1    BarType = 86400
)

var EnumNamesBarType = map[BarType]string{
	BarTypeDefault: "Default",
	BarTypeMin1:    "Min1",
	BarTypeMin5:    "Min5",
	BarTypeMin15:   "Min15",
	BarTypeMin30:   "Min30",
	BarTypeMin60:   "Min60",
	BarTypeDay1:    "Day1",
}

var EnumValuesBarType = map[string]BarType{
	"Default": BarTypeDefault,
	"Min1":    BarTypeMin1,
	"Min5":    BarTypeMin5,
	"Min15":   BarTypeMin15,
	"Min30":   BarTypeMin30,
	"Min60":   BarTypeMin60,
	"Day1":    BarTypeDay1,
}

func (v BarType) String() string {
	if s, ok := EnumNamesBarType[v]; ok {
		return s
	}
	return "BarType(" + strconv.FormatInt(int64(v), 10) + ")"
}
