// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CancelOrderCommandT struct {
	Time int64 `json:"time"`
	Order *OrderT `json:"order"`
}

func (t *CancelOrderCommandT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	orderOffset := t.Order.Pack(builder)
	CancelOrderCommandStart(builder)
	CancelOrderCommandAddTime(builder, t.Time)
	CancelOrderCommandAddOrder(builder, orderOffset)
	return CancelOrderCommandEnd(builder)
}

func (rcv *CancelOrderCommand) UnPackTo(t *CancelOrderCommandT) {
	t.Time = rcv.Time()
	t.Order = rcv.Order(nil).UnPack()
}

func (rcv *CancelOrderCommand) UnPack() *CancelOrderCommandT {
	if rcv == nil {
		return nil
	}
	t := &CancelOrderCommandT{}
	rcv.UnPackTo(t)
	return t
}

type CancelOrderCommand struct {
	_tab flatbuffers.Table
}

func GetRootAsCancelOrderCommand(buf []byte, offset flatbuffers.UOffsetT) *CancelOrderCommand {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CancelOrderCommand{}
	x.Init(buf, n+offset)
	return x
}

func FinishCancelOrderCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsCancelOrderCommand(buf []byte, offset flatbuffers.UOffsetT) *CancelOrderCommand {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CancelOrderCommand{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedCancelOrderCommandBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *CancelOrderCommand) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CancelOrderCommand) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CancelOrderCommand) Time() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CancelOrderCommand) MutateTime(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *CancelOrderCommand) Order(obj *Order) *Order {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Order)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CancelOrderCommandStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CancelOrderCommandAddTime(builder *flatbuffers.Builder, time int64) {
	builder.PrependInt64Slot(0, time, 0)
}
func CancelOrderCommandAddOrder(builder *flatbuffers.Builder, order flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(order), 0)
}
func CancelOrderCommandEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
