// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type FeeRateOffset int16

const (
	FeeRateOffsetDEFAULT       FeeRateOffset = 0
	FeeRateOffsetOPEN          FeeRateOffset = 1
	FeeRateOffsetCLOSE         FeeRateOffset = 2
	FeeRateOffsetCLOSE_TODAY   FeeRateOffset = 3
	FeeRateOffsetCLOSE_HISTORY FeeRateOffset = 4
)

var EnumNamesFeeRateOffset = map[FeeRateOffset]string{
	FeeRateOffsetDEFAULT:       "DEFAULT",
	FeeRateOffsetOPEN:          "OPEN",
	FeeRateOffsetCLOSE:         "CLOSE",
	FeeRateOffsetCLOSE_TODAY:   "CLOSE_TODAY",
	FeeRateOffsetCLOSE_HISTORY: "CLOSE_HISTORY",
}

var EnumValuesFeeRateOffset = map[string]FeeRateOffset{
	"DEFAULT":       FeeRateOffsetDEFAULT,
	"OPEN":          FeeRateOffsetOPEN,
	"CLOSE":         FeeRateOffsetCLOSE,
	"CLOSE_TODAY":   FeeRateOffsetCLOSE_TODAY,
	"CLOSE_HISTORY": FeeRateOffsetCLOSE_HISTORY,
}

func (v FeeRateOffset) String() string {
	if s, ok := EnumNamesFeeRateOffset[v]; ok {
		return s
	}
	return "FeeRateOffset(" + strconv.FormatInt(int64(v), 10) + ")"
}
