// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type FeeRateAction int16

const (
	FeeRateActionBUY    FeeRateAction = 0
	FeeRateActionSELL   FeeRateAction = 1
	FeeRateActionCANCEL FeeRateAction = 2
)

var EnumNamesFeeRateAction = map[FeeRateAction]string{
	FeeRateActionBUY:    "BUY",
	FeeRateActionSELL:   "SELL",
	FeeRateActionCANCEL: "CANCEL",
}

var EnumValuesFeeRateAction = map[string]FeeRateAction{
	"BUY":    FeeRateActionBUY,
	"SELL":   FeeRateActionSELL,
	"CANCEL": FeeRateActionCANCEL,
}

func (v FeeRateAction) String() string {
	if s, ok := EnumNamesFeeRateAction[v]; ok {
		return s
	}
	return "FeeRateAction(" + strconv.FormatInt(int64(v), 10) + ")"
}
