// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type OrderType uint16

const (
	/// 0 限价单
	OrderTypeLIMIT  OrderType = 0
	/// 1 市价单
	OrderTypeMARKET OrderType = 1
)

var EnumNamesOrderType = map[OrderType]string{
	OrderTypeLIMIT:  "LIMIT",
	OrderTypeMARKET: "MARKET",
}

var EnumValuesOrderType = map[string]OrderType{
	"LIMIT":  OrderTypeLIMIT,
	"MARKET": OrderTypeMARKET,
}

func (v OrderType) String() string {
	if s, ok := EnumNamesOrderType[v]; ok {
		return s
	}
	return "OrderType(" + strconv.FormatInt(int64(v), 10) + ")"
}
