// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type OrderStatus uint16

const (
	/// 0 待报
	OrderStatusPENDING       OrderStatus = 0
	/// 1 已报
	OrderStatusQUEUED        OrderStatus = 1
	/// 2 正在撤
	OrderStatusCANCELING     OrderStatus = 2
	/// 3 部分成交
	OrderStatusFILLING       OrderStatus = 3
	/// 4 部成部撤
	OrderStatusPART_CANCELED OrderStatus = 4
	/// 5 全撤
	OrderStatusCANCELED      OrderStatus = 5
	/// 6 全成
	OrderStatusFILLED        OrderStatus = 6
	/// 7 拒单，参考OrderErrorType
	OrderStatusREJECTED      OrderStatus = 7
)

var EnumNamesOrderStatus = map[OrderStatus]string{
	OrderStatusPENDING:       "PENDING",
	OrderStatusQUEUED:        "QUEUED",
	OrderStatusCANCELING:     "CANCELING",
	OrderStatusFILLING:       "FILLING",
	OrderStatusPART_CANCELED: "PART_CANCELED",
	OrderStatusCANCELED:      "CANCELED",
	OrderStatusFILLED:        "FILLED",
	OrderStatusREJECTED:      "REJECTED",
}

var EnumValuesOrderStatus = map[string]OrderStatus{
	"PENDING":       OrderStatusPENDING,
	"QUEUED":        OrderStatusQUEUED,
	"CANCELING":     OrderStatusCANCELING,
	"FILLING":       OrderStatusFILLING,
	"PART_CANCELED": OrderStatusPART_CANCELED,
	"CANCELED":      OrderStatusCANCELED,
	"FILLED":        OrderStatusFILLED,
	"REJECTED":      OrderStatusREJECTED,
}

func (v OrderStatus) String() string {
	if s, ok := EnumNamesOrderStatus[v]; ok {
		return s
	}
	return "OrderStatus(" + strconv.FormatInt(int64(v), 10) + ")"
}
