// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type RpcMsgType int16

const (
	RpcMsgTypeERR  RpcMsgType = -1
	RpcMsgTypeCONN RpcMsgType = 0
	RpcMsgTypeACPT RpcMsgType = 1
	RpcMsgTypeREQ  RpcMsgType = 2
	RpcMsgTypeRSP  RpcMsgType = 3
	RpcMsgTypeACK  RpcMsgType = 4
	RpcMsgTypePUB  RpcMsgType = 5
	RpcMsgTypeLEFT RpcMsgType = 6
)

var EnumNamesRpcMsgType = map[RpcMsgType]string{
	RpcMsgTypeERR:  "ERR",
	RpcMsgTypeCONN: "CONN",
	RpcMsgTypeACPT: "ACPT",
	RpcMsgTypeREQ:  "REQ",
	RpcMsgTypeRSP:  "RSP",
	RpcMsgTypeACK:  "ACK",
	RpcMsgTypePUB:  "PUB",
	RpcMsgTypeLEFT: "LEFT",
}

var EnumValuesRpcMsgType = map[string]RpcMsgType{
	"ERR":  RpcMsgTypeERR,
	"CONN": RpcMsgTypeCONN,
	"ACPT": RpcMsgTypeACPT,
	"REQ":  RpcMsgTypeREQ,
	"RSP":  RpcMsgTypeRSP,
	"ACK":  RpcMsgTypeACK,
	"PUB":  RpcMsgTypePUB,
	"LEFT": RpcMsgTypeLEFT,
}

func (v RpcMsgType) String() string {
	if s, ok := EnumNamesRpcMsgType[v]; ok {
		return s
	}
	return "RpcMsgType(" + strconv.FormatInt(int64(v), 10) + ")"
}
