// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type SectorType uint16

const (
	/// 未知
	SectorTypeUnknown  SectorType = 0
	///49:上海A股；
	SectorTypeAShareSH SectorType = 49
	///50:深圳A股；
	SectorTypeAShareSZ SectorType = 50
	///51:上海B股；
	SectorTypeBShareSH SectorType = 51
	///52:深圳B股；
	SectorTypeBShareSZ SectorType = 52
	///53:三板A股；
	SectorTypeAShareSB SectorType = 53
	///100:港股期货；
	SectorTypeFutureHK SectorType = 100
	///101:北交所A股；
	SectorTypeAShareBJ SectorType = 101
	///107:美股指数；
	SectorTypeIndexUS  SectorType = 107
	///109:纽约证券交易所（NYSE）
	SectorTypeNYSE     SectorType = 109
	///110:纳斯达克交易所（NASDAQ）； 
	SectorTypeNASDAQ   SectorType = 110
	///114:中国金融期货交易所；
	SectorTypeCF       SectorType = 114
	///115:上海商品期货；
	SectorTypeSHF      SectorType = 115
	///116:郑州商品期货；
	SectorTypeCZC      SectorType = 116
	///117:大连商品期货
	SectorTypeDCE      SectorType = 117
	///118:上海国际能源交易中心.
	SectorTypeINE      SectorType = 118
)

var EnumNamesSectorType = map[SectorType]string{
	SectorTypeUnknown:  "Unknown",
	SectorTypeAShareSH: "AShareSH",
	SectorTypeAShareSZ: "AShareSZ",
	SectorTypeBShareSH: "BShareSH",
	SectorTypeBShareSZ: "BShareSZ",
	SectorTypeAShareSB: "AShareSB",
	SectorTypeFutureHK: "FutureHK",
	SectorTypeAShareBJ: "AShareBJ",
	SectorTypeIndexUS:  "IndexUS",
	SectorTypeNYSE:     "NYSE",
	SectorTypeNASDAQ:   "NASDAQ",
	SectorTypeCF:       "CF",
	SectorTypeSHF:      "SHF",
	SectorTypeCZC:      "CZC",
	SectorTypeDCE:      "DCE",
	SectorTypeINE:      "INE",
}

var EnumValuesSectorType = map[string]SectorType{
	"Unknown":  SectorTypeUnknown,
	"AShareSH": SectorTypeAShareSH,
	"AShareSZ": SectorTypeAShareSZ,
	"BShareSH": SectorTypeBShareSH,
	"BShareSZ": SectorTypeBShareSZ,
	"AShareSB": SectorTypeAShareSB,
	"FutureHK": SectorTypeFutureHK,
	"AShareBJ": SectorTypeAShareBJ,
	"IndexUS":  SectorTypeIndexUS,
	"NYSE":     SectorTypeNYSE,
	"NASDAQ":   SectorTypeNASDAQ,
	"CF":       SectorTypeCF,
	"SHF":      SectorTypeSHF,
	"CZC":      SectorTypeCZC,
	"DCE":      SectorTypeDCE,
	"INE":      SectorTypeINE,
}

func (v SectorType) String() string {
	if s, ok := EnumNamesSectorType[v]; ok {
		return s
	}
	return "SectorType(" + strconv.FormatInt(int64(v), 10) + ")"
}
