// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type TradeAttribute uint16

const (
	///0:未处理的默认值；
	TradeAttributeDefault TradeAttribute = 0
	///10:T+0交易；
	TradeAttributeT0      TradeAttribute = 10
	///11:T+1交易；
	TradeAttributeT1      TradeAttribute = 11
	///12:T+2交易；
	TradeAttributeT2      TradeAttribute = 12
)

var EnumNamesTradeAttribute = map[TradeAttribute]string{
	TradeAttributeDefault: "Default",
	TradeAttributeT0:      "T0",
	TradeAttributeT1:      "T1",
	TradeAttributeT2:      "T2",
}

var EnumValuesTradeAttribute = map[string]TradeAttribute{
	"Default": TradeAttributeDefault,
	"T0":      TradeAttributeT0,
	"T1":      TradeAttributeT1,
	"T2":      TradeAttributeT2,
}

func (v TradeAttribute) String() string {
	if s, ok := EnumNamesTradeAttribute[v]; ok {
		return s
	}
	return "TradeAttribute(" + strconv.FormatInt(int64(v), 10) + ")"
}
