// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package data

import "strconv"

type TransitSide int16

const (
	/// 0 转入
	TransitSideDEPOSIT  TransitSide = 0
	/// 1 转出
	TransitSideWITHDRAW TransitSide = 1
)

var EnumNamesTransitSide = map[TransitSide]string{
	TransitSideDEPOSIT:  "DEPOSIT",
	TransitSideWITHDRAW: "WITHDRAW",
}

var EnumValuesTransitSide = map[string]TransitSide{
	"DEPOSIT":  TransitSideDEPOSIT,
	"WITHDRAW": TransitSideWITHDRAW,
}

func (v TransitSide) String() string {
	if s, ok := EnumNamesTransitSide[v]; ok {
		return s
	}
	return "TransitSide(" + strconv.FormatInt(int64(v), 10) + ")"
}
